alias e='emacsclient -a "" -t'
alias et='emacsclient -a "" -t'
alias ec='emacsclient -a "" -c'
alias en='emacsclient -a "" -c -n'
export EDITOR='emacsclient -a "" -t'
export SUDOEDITOR='emacsclient -a "" -c -n'
export VISUAL='emacsclient -a "" -c -n'
export GIT_EDITOR='emacsclient -a "" -c -n'
