alias agi='sudo apt-get install'
alias agr='sudo apt-get remove'
alias agp='sudo apt-get purge'
alias acs='sudo apt-cache search'
alias agu='sudo apt-get update'
alias adu='sudo apt-get upgrade'
alias ads='sudo apt-get dist-upgrade'
