call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-surround'
Plug 'benekastah/neomake'
Plug 'bling/vim-airline'
Plug 'jordwalke/flatlandia'

" Syntax
Plug 'cespare/vim-toml'
Plug 'tpope/vim-git'
Plug 'pangloss/vim-javascript'
Plug 'mmalecki/vim-node.js'
Plug 'vim-ruby/vim-ruby'
Plug 'ChrisYip/Better-CSS-Syntax-for-Vim'
Plug 'othree/html5.vim'
Plug 'klen/python-mode'
Plug 'rodjek/vim-puppet'
Plug 'sophacles/vim-processing'
Plug 'vim-pandoc/vim-pantondoc'
Plug 'vim-pandoc/vim-pandoc-syntax'
Plug 'chilicuil/vim-sml-coursera'

call plug#end()

" Configuration
colorscheme gruvbox
let mapleader = ","
"let LocalLeader = ";"
noremap <leader>w :w<CR>
noremap <leader>W :w!sudo tee %
noremap <leader>q :q<CR>
noremap <leader>ev :vsplit ./
noremap <leader>eh :split ./

noremap <leader>uf :Unite file<CR>
noremap <leader>ub :Unite buffer<CR>

nnoremap ' `
nnoremap <Leader>G <Plug>(golden_ratio_resize)

nnoremap ` '
nnoremap <Leader>S :%s//<left>
inoremap jj <Esc>
"" TABBING
set tabstop=4
" Set soft tabs equal to 4 spaces.
set softtabstop=4
" Set auto indent spacing.
set shiftwidth=4
" automatically change directories when opening files
" set autochdir
" " Shift to the next round tab stop.
set shiftround
set smartindent
set smarttab
set expandtab
set nolist
" List of characters to show instead of whitespace.
set listchars=tab:▸\ ,eol:¬,trail:⌴,extends:❯,precedes:❮
let &showbreak=nr2char(8618).' '
set linebreak
set ttyfast
set ruler
set showmatch
set matchtime=3
set matchpairs+=<:>
set printoptions+=syntax:y
set printoptions+=number:y
set cf
set foldmethod=indent   "fold based on indent
set foldnestmax=3       "deepest fold is 3 levels
" set nofoldenable
if has ('mouse')
    set mouse=a
    set mousemodel=popup_setpos
    " Hide mouse while typing.
    set mousehide"
    if &term =~ "xterm" || &term =~ "screen"
        set ttymouse=xterm2
    endif
endif
"" Use ctrl-[hjkl] to select the active split
nmap <silent> <c-k> :wincmd k<CR>
nmap <silent> <c-j> :wincmd j<CR>
nmap <silent> <c-h> :wincmd h<CR>
nmap <silent> <c-l> :wincmd l<CR>
" Fold opening and closing
nmap <leader>. za
map <leader>. za

" Tab maneuvering
nmap <leader>tn :tabnext<CR>
map <leader>tn :tabnext<CR>
nmap <leader>tp :tabprevious<CR>
map <leader>tp :tabprevious<CR>
nnoremap <leader>nt :tabnew ./
" Airline setup for statusbar
let g:airline#extensions#tabline#enabled = 1

"let g:airline_powerline_fonts = 1
set laststatus=2
" Disable truncation
let g:airline#extensions#default#section_truncate_width = {}

