" Vimpager or Diff {{{
if &diff || exists("vimpager")
  set diffopt+=iwhite
  set noloadplugins
else
  source ~/.nvim-conf/nvimrc.plugin_settings
  source ~/.nvim-conf/nvimrc.plugins
  source ~/.nvim-conf/nvimrc.base
  source ~/.nvim-conf/nvimrc.misc
  source ~/.nvim-conf/nvimrc.theme
  source ~/.nvim-conf/nvimrc.status
  source ~/.nvim-conf/nvimrc.keys
  source ~/.nvim-conf/nvimrc.autocmds
endif
