set nocompatible               " be iMproved
filetype off                   " required!

" set rtp +=~/.vim.local/
if has('vim_starting')
    set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#rc(expand('~/.vim/bundle/'))

" Let NeoBundle manage NeoBundle
NeoBundleFetch 'shougo/neobundle.vim'

" Recommended to install
" After install, turn shell ~/.vim/bundle/vimproc, (n,g)make -f
" your_machines_makefile
NeoBundle 'shougo/vimproc'"


"" Plugins
NeoBundle "shougo/unite.vim"

NeoBundle 'rstacruz/sparkup', {'rtp': 'vim/'}

NeoBundle 'Lokaltog/vim-easymotion'
NeoBundle 'bling/vim-airline'

" Completion interface
NeoBundle "shougo/neocomplete.vim"

" Git setup
NeoBundle 'tpope/vim-fugitive'

" Colors hex values in CSS files
NeoBundle 'ap/vim-css-color'

" Autocloses if->endif, etc...
NeoBundle 'tpope/vim-endwise'

" Allows changing surrounding delimeters
NeoBundle 'tpope/vim-surround'

" Allows more things to be '.'ed
NeoBundle 'tpope/vim-repeat'

" Vim personal wiki. hooked into trunknotes for me
NeoBundle 'vim-scripts/vimwiki'

NeoBundle 'vim-scripts/ShowMarks7'

" Better pasting
NeoBundle 'sickill/vim-pasta'

" Colors parens
NeoBundle 'kien/rainbow_parentheses.vim'

" Automatically closes quotes, parenthesis, brackets, etc.
NeoBundle 'Raimondi/delimitMate'

NeoBundle 'nathanaelkane/vim-indent-guides'

" 3-way merge manager
NeoBundle 'sjl/splice.vim'

" Indent finder
NeoBundle 'Raimondi/YAIFA'

" looks for todos
NeoBundle 'vim-scripts/TaskList.vim'

" Matching if/endif, not just {} [] ()
NeoBundle 'vim-scripts/matchit.zip'

" Syntastic for syntax checking
NeoBundle 'scrooloose/syntastic'

" Window Management
NeoBundle 'spolu/dwm.vim'

"" Syntaxes
" NeoBundle 'vim-scripts/Arduino-syntax-file'
NeoBundle 'tpope/vim-git'
NeoBundle 'tpope/vim-haml'
NeoBundle 'pangloss/vim-javascript'
NeoBundle 'mmalecki/vim-node.js'
NeoBundle 'vim-ruby/vim-ruby'
NeoBundle 'ChrisYip/Better-CSS-Syntax-for-Vim'
NeoBundle 'othree/html5.vim'
NeoBundle 'nblock/vim-dokuwiki'
NeoBundle 'klen/python-mode'
NeoBundle 'rodjek/vim-puppet'


" Colors
NeoBundle 'altercation/vim-colors-solarized'

" Tab management
NeoBundle 'kien/tabman.vim'

NeoBundleCheck

" Configuration
syntax on        " turn on hilighting
"let g:Powerline_symbols = 'fancy'
"let g:Powerline_stl_path_style = 'filename'
"let g:Powerline_theme = 'solarized'
"let g:Powerline_colorscheme = 'solarized'
"set encoding=utf-8
" set fillchars+=stl:\ ,stlnc:\
set laststatus=2
set t_Co=256
set number
set showmode
set showcmd
set splitbelow
set splitright
"set visualbell
set hidden
set ignorecase
set smartcase
"filetype plugin on
filetype indent on
filetype plugin indent on
let mapleader = ","
"let LocalLeader = ";"
noremap <leader>w :w<CR>
noremap <leader>W :w!sudo tee %
noremap <leader>q :q<CR>
noremap <leader>ev :vsplit ./
noremap <leader>eh :vsplit ./
nnoremap ' `
nnoremap <Leader>G <Plug>(golden_ratio_resize)

nnoremap ` '
nnoremap <Leader>S :%s//<left>
inoremap jj <Esc>

set backup
set autowrite
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set backspace=indent,eol,start

" Highlight search terms...
set hlsearch
set incsearch
set shortmess=atI
set modelines=0
set autoindent
set wrap

"" TABBING
set tabstop=4
" Set soft tabs equal to 4 spaces.
set softtabstop=4
" Set auto indent spacing.
set shiftwidth=4
" automatically change directories when opening files
" set autochdir
" " Shift to the next round tab stop.
set shiftround
set smartindent
set smarttab
set expandtab
set nolist
"
" List of characters to show instead of whitespace.
set listchars=tab:▸\ ,eol:¬,trail:⌴,extends:❯,precedes:❮
let &showbreak=nr2char(8618).' '
set linebreak
set ttyfast
set ruler
set showmatch
set matchtime=3
set matchpairs+=<:>
set printoptions+=syntax:y
set printoptions+=number:y
set cf
set foldmethod=indent   "fold based on indent
set foldnestmax=3       "deepest fold is 3 levels
" set nofoldenable

set wildmenu

" Enable completion on tab.
set wildchar=<Tab>

" Insert mode completion.
set completeopt=longest,menu,preview

" Wildcard expansion completion.
set wildmode=list:longest,list:full

" Keyword completion for when Ctrl-P and Ctrl-N are pressed.
set complete=.,t

" Completion Ignored Files -----------------------------------------------

" VCS directories.
set wildignore+=.hg,.git,.svn

" LaTeX intermediate files.
set wildignore+=*.aux,*.out,*.toc

" Binary images.
set wildignore+=*.jpg,*.bmp,*.gif,*.png,*.jpeg

" Lua byte code.
set wildignore+=*.luac

" Compiled object files.
set wildignore+=*.o,*.obj,*.exe,*.dll,*.manifest

" Python byte code.
set wildignore+=*.pyc

" Compiled spelling lists.
set wildignore+=*.spl

" Backup, auto save, swap, undo, and view files.
set wildignore+=*~,#*#,*.sw?,%*,*=

" Mac OS X.
set wildignore+=*.DS_Store

"set runtimepath+=~/.vim.local
"let $PAGER=''
color solarized
set background=dark
call togglebg#map("<F6>")
let g:solarized_termcolors=16
set t_Co=16

if has ('mouse')
    set mouse=a
    set mousemodel=popup_setpos
    " Hide mouse while typing.
    set mousehide"
    if &term =~ "xterm" || &term =~ "screen"
        set ttymouse=xterm2
    endif
endif

"" Use ctrl-[hjkl] to select the active split!
" nmap <silent> <c-k> :wincmd k<CR>
" nmap <silent> <c-j> :wincmd j<CR>
" nmap <silent> <c-h> :wincmd h<CR>
" nmap <silent> <c-l> :wincmd l<CR>

" Fold opening and closing
nmap <leader>. za
map <leader>. za

set clipboard=unnamed
"
" Yank text to the OS X clipboard
noremap <leader>y "*y
noremap <leader>yy "*Y

" Preserve indentation while pasting text from the OS X clipboard
noremap <leader>p :set paste<CR>:put  *<CR>:set nopaste<CR>

" Map :tabnext and :tabprevious to make tab hopping easy
nnoremap <C-h> :tabp<CR>
nnoremap <C-l> :tabn<CR>
nnoremap <leader>nt :tabnew ./

" kill all trailing whitespace
autocmd BufWritePre * :%s/\s\+$//e

let g:html_indent_inctags = "html,body,head,tbody,div"
let g:html_indent_script1 = "inc"
let g:html_indent_style1 = "inc"

let g:vimwiki_list = [
            \ {'path': '~/Dropbox/trunksync/notes/ ', 'index': 'HomePage', 'path_html': '~/trunknotes_html', 'ext': '.markdown', 'auto_export': 0}
            \ ]
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"
let g:extradite_showhash = 1
let g:ctrlp_working_path_mode = 2
let g:ctrlp_root_markers = ['.git']
let g:ctrlp_max_height = 10
let g:ctrlp_persistent_input = 0
let g:ctrlp_lazy_update = 1
let g:ctrlp_extensions = ['tag', 'buffertag', 'quickfix', 'dir']

let g:syntastic_quiet_warnings = 0

" Do not validate the following file types.
let g:syntastic_disabled_filetypes = ['html', 'python']
"
" Set the display format.
let g:syntastic_stl_format = '[%E{Err: %fe #%e}%B{, }%W{Warn: %fw #%w}]'
let g:syntastic_always_populate_loc_list=0

let g:EasyMotion_leader_key = ';'

"" Python-Mode setup
" disable pylint on every save
"let g:pymode_lint_write = 0
" Press <leader>d to show docs
let g:pymode_doc_key = '<leader>d'


"" AUTOCOMMANDS
au VimResized * exe "normal! \<c-w>="
aug cursorline
    au!
    au BufEnter * set cursorline
    au BufLeave * set nocursorline
    au InsertEnter * set nocursorline
    au InsertLeave * set cursorline
aug end

" Stop putting python comments at the beginning of a line
au! FileType python setl nosmartindent

" Save and load fold states
au BufWinLeave * mkview
au BufWinEnter * silent loadview

"" NeoComplete
"Note: This option must set it in .vimrc(_vimrc).  NOT IN .gvimrc(_gvimrc)!
" Disable AutoComplPop.
let g:acp_enableAtStartup = 0
" Use neocomplete.
let g:neocomplete#enable_at_startup = 1
" Use smartcase.
let g:neocomplete#enable_smart_case = 1
" Set minimum syntax keyword length.
let g:neocomplete#sources#syntax#min_keyword_length = 3
let g:neocomplete#lock_buffer_name_pattern = '\*ku\*'

" Define dictionary.
let g:neocomplete#sources#dictionary#dictionaries = {
            \ 'default' : '',
            \ 'vimshell' : $HOME.'/.vimshell_hist',
            \ 'scheme' : $HOME.'/.gosh_completions'
            \ }

" Define keyword.
if !exists('g:neocomplete#keyword_patterns')
    let g:neocomplete#keyword_patterns = {}
endif
let g:neocomplete#keyword_patterns['default'] = '\h\w*'

" Plugin key-mappings.
inoremap <expr><C-g>     neocomplete#undo_completion()
inoremap <expr><C-l>     neocomplete#complete_common_string()

" Recommended key-mappings.
" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
    return neocomplete#smart_close_popup() . "\<CR>"
    " For no inserting <CR> key.
    "return pumvisible() ? neocomplete#close_popup() : "\<CR>"
endfunction
" <TAB>: completion.
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
" <C-h>, <BS>: close popup and delete backword char.
inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><C-y>  neocomplete#close_popup()
inoremap <expr><C-e>  neocomplete#cancel_popup()
" Close popup by <Space>.
"inoremap <expr><Space> pumvisible() ? neocomplete#close_popup() :
""\<Space>"

" For cursor moving in insert mode(Not recommended)
"inoremap <expr><Left>  neocomplete#close_popup() . "\<Left>"
"inoremap <expr><Right> neocomplete#close_popup() . "\<Right>"
"inoremap <expr><Up>    neocomplete#close_popup() . "\<Up>"
"inoremap <expr><Down>  neocomplete#close_popup() . "\<Down>"
" Or set this.
"let g:neocomplete#enable_cursor_hold_i = 1
" Or set this.
"let g:neocomplete#enable_insert_char_pre = 1

" AutoComplPop like behavior.
"let g:neocomplete#enable_auto_select = 1

" Shell like behavior(not recommended).
"set completeopt+=longest
"let g:neocomplete#enable_auto_select = 1
"let g:neocomplete#disable_auto_complete = 1
"inoremap <expr><TAB>  pumvisible() ? "\<Down>" : "\<C-x>\<C-u>"

" Enable omni completion.
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

" Enable heavy omni completion.
if !exists('g:neocomplete#sources#omni#input_patterns')
    let g:neocomplete#sources#omni#input_patterns = {}
endif
let g:neocomplete#sources#omni#input_patterns.php = '[^.\t]->\h\w*\|\h\w*::'
let g:neocomplete#sources#omni#input_patterns.c = '[^.[:digit:]*\t]\%(\.\|->\)'
let g:neocomplete#sources#omni#input_patterns.cpp = '[^.[:digit:]*\t]\%(\.\|->\)\|\h\w*::'

" For perlomni.vim setting.
" https://github.com/c9s/perlomni.vim
let g:neocomplete#sources#omni#input_patterns.perl ='\h\w*->\h\w*\|\h\w*::'

"" Unite.vim
" Act like ctrlp.vim
nnoremap <C-p> :Unite file_rec/async<cr>
nnoremap <space>/ :Unite ag:.<cr>

" Buffer swapping like lustyjuggler
nnoremap <space>s :Unite -quick-match buffer<cr>
