#!/bin/sh
# Start Gnome Polkit authentication agent.
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

# XResources and setup
xrdb -merge $HOME/.Xresources
xset +fp /usr/share/fonts/local
xset fp rehash
xscreensaver &
xmodmap $HOME/.Xmodmap

# Set up displays
sh $HOME/.screenlayout/default.sh

# Start Applications
urxvtd -q -f -o &
feh --bg-scale $HOME/Pictures/ssep.png
pidgin &
#start-ipython-notebook &

# Set up windows
exec dwmloop
