# Load zgen
source "${HOME}/.zgen.zsh"
if ! zgen saved; then
    echo "Creating a zgen save"

    zgen load zsh-users/zsh-syntax-highlighting

    # Themes
    zgen oh-my-zsh themes/theunraveler #sunrise # gallois

    # Save it to an init script
    zgen save
fi

# Completions
fpath=(~/.zsh $fpath)

# load fresh-built files
source ~/.fresh/build/shell.sh
