# Path to your oh-my-zsh configuration.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

ZSH_THEME="agnoster"

plugins=(git ssh-agent)
source ~/.fresh/build/shell.sh
fpath=(~/.zsh $fpath)
