# Path to your oh-my-zsh configuration.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

ZSH_THEME="gallois"

plugins=(git)

test -d ~/secrets && source ~/.secrets/*.sh #secrets!

source ~/.fresh/build/shell.sh
